vich_uploader: 
  db_driver: orm

  mappings:
        product_images:
            uri_prefix: /upload/images/products
            upload_destination: '%kernel.project_dir%/public/upload/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true