catalog:
  path: /
  controller: App\Controller\CatalogController::index

app_logout:
    path: /logout
    methods: GET
    controller: App\Controller\SecurityController::login
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
